### ISSUE TITLE
Style error when installing account_report_cbc module

### ISSUE THREAD

**Issue by hgati** [CubicERP/apps#5]
![snap1](https://user-images.githubusercontent.com/6913728/37915482-9a322af8-3154-11e8-9936-f735233997bf.png)

Odoo 11.0 install error

**Comment by bennals** [comment]
@hgati why was this issue closed?  Did you resolve the problem?  I'm having the same problem and I see others have had similar issues since late 2017 but no-one has posted about the solution.
